databases:
  - name: movies-db
    databaseName: movies_db
    user: movies_user

services:
  - type: web
    name: movies-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: movies-db
          property: connectionString
      - key: NODE_ENV
        value: production